
export enum QUESTION_TYPE {
    SINGLE = 'SINGLE',
    MULTIPLE = 'MULTIPLE',
    MIXED = 'MIXED'
}

export const QUESTION_TYPE_LABELS = {
  [QUESTION_TYPE.SINGLE]: '单选',
  [QUESTION_TYPE.MULTIPLE]: '多选',
  [QUESTION_TYPE.MIXED]: 'Mixed',
}
